"""add the project_category and  project_stage schemas

Revision ID: 329801250842
Revises: 4707b3ca9c07
Create Date: 2025-11-19 17:25:37.935619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329801250842'
down_revision: Union[str, Sequence[str], None] = '4707b3ca9c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_category_master', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('project_category_master', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('project_stage_master', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('project_stage_master', sa.Column('updated_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_stage_master', 'updated_by')
    op.drop_column('project_stage_master', 'created_by')
    op.drop_column('project_category_master', 'updated_by')
    op.drop_column('project_category_master', 'created_by')
    # ### end Alembic commands ###
