"""added some extra columns in projects and projectdrafts

Revision ID: 8adfb81764cd
Revises: 44108aea6705
Create Date: 2025-12-12 16:10:56.320406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adfb81764cd'
down_revision: Union[str, Sequence[str], None] = '44108aea6705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perdix_mp_project_drafts', sa.Column('funding_type', sa.String(length=100), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('commitment_allocation_days', sa.Integer(), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('minimum_commitment_fulfilment_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('mode_of_implementation', sa.String(length=100), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('ownership', sa.String(length=100), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('tenure', sa.Integer(), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('cut_off_rate_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('minimum_commitment_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('perdix_mp_project_drafts', sa.Column('conditions', sa.Text(), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('funding_type', sa.String(length=100), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('commitment_allocation_days', sa.Integer(), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('minimum_commitment_fulfilment_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('mode_of_implementation', sa.String(length=100), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('ownership', sa.String(length=100), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('tenure', sa.Integer(), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('cut_off_rate_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('minimum_commitment_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('perdix_mp_projects', sa.Column('conditions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perdix_mp_projects', 'conditions')
    op.drop_column('perdix_mp_projects', 'minimum_commitment_amount')
    op.drop_column('perdix_mp_projects', 'cut_off_rate_percentage')
    op.drop_column('perdix_mp_projects', 'tenure')
    op.drop_column('perdix_mp_projects', 'ownership')
    op.drop_column('perdix_mp_projects', 'mode_of_implementation')
    op.drop_column('perdix_mp_projects', 'minimum_commitment_fulfilment_percentage')
    op.drop_column('perdix_mp_projects', 'commitment_allocation_days')
    op.drop_column('perdix_mp_projects', 'funding_type')
    op.drop_column('perdix_mp_project_drafts', 'conditions')
    op.drop_column('perdix_mp_project_drafts', 'minimum_commitment_amount')
    op.drop_column('perdix_mp_project_drafts', 'cut_off_rate_percentage')
    op.drop_column('perdix_mp_project_drafts', 'tenure')
    op.drop_column('perdix_mp_project_drafts', 'ownership')
    op.drop_column('perdix_mp_project_drafts', 'mode_of_implementation')
    op.drop_column('perdix_mp_project_drafts', 'minimum_commitment_fulfilment_percentage')
    op.drop_column('perdix_mp_project_drafts', 'commitment_allocation_days')
    op.drop_column('perdix_mp_project_drafts', 'funding_type')
    # ### end Alembic commands ###
