"""added some functionality

Revision ID: a719f4d37be3
Revises: 57d7c48697c8
Create Date: 2025-12-12 18:07:13.526284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a719f4d37be3'
down_revision: Union[str, Sequence[str], None] = '57d7c48697c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perdix_mp_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("access_level IN ('public', 'restricted', 'private')", name='check_access_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perdix_mp_files_id'), 'perdix_mp_files', ['id'], unique=False)
    op.create_table('perdix_mp_users_details',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_mobile_number', sa.String(length=20), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('is_tc_accepted', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('gstn_ulb_code', sa.String(length=50), nullable=True),
    sa.Column('annual_budget_size', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('mobile_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['perdix_mp_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perdix_mp_users_details_id'), 'perdix_mp_users_details', ['id'], unique=False)
    op.create_index(op.f('ix_perdix_mp_users_details_user_id'), 'perdix_mp_users_details', ['user_id'], unique=True)
    op.drop_index(op.f('ix_dummy_table_id'), table_name='dummy_table')
    op.drop_table('dummy_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_table',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dummy_table_pkey'))
    )
    op.create_index(op.f('ix_dummy_table_id'), 'dummy_table', ['id'], unique=False)
    op.drop_index(op.f('ix_perdix_mp_users_details_user_id'), table_name='perdix_mp_users_details')
    op.drop_index(op.f('ix_perdix_mp_users_details_id'), table_name='perdix_mp_users_details')
    op.drop_table('perdix_mp_users_details')
    op.drop_index(op.f('ix_perdix_mp_files_id'), table_name='perdix_mp_files')
    op.drop_table('perdix_mp_files')
    # ### end Alembic commands ###
