"""added the model project

Revision ID: b23a0f36cd2b
Revises: dbf6b736cc4c
Create Date: 2025-11-17 10:59:04.768968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b23a0f36cd2b'
down_revision: Union[str, Sequence[str], None] = 'dbf6b736cc4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perdix_mp_projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_type', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('project_reference_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('project_stage', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_project_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('funding_requirement', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('already_secured_funds', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commitment_gap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('fundraising_start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fundraising_end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('municipality_credit_rating', sa.String(length=20), nullable=True),
    sa.Column('municipality_credit_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('funding_raised', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('funding_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("project_stage IN ('planning', 'initiated', 'in_progress')", name='check_project_stage'),
    sa.CheckConstraint("status IN ('draft', 'pending_validation', 'active', 'funding_completed', 'closed', 'rejected')", name='check_status'),
    sa.CheckConstraint("visibility IN ('private', 'public')", name='check_visibility'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perdix_mp_projects_id'), 'perdix_mp_projects', ['id'], unique=False)
    op.create_index(op.f('ix_perdix_mp_projects_project_reference_id'), 'perdix_mp_projects', ['project_reference_id'], unique=True)
    
    # Drop dependent tables first (in order of dependencies)
    # settlement_logs depends on commitments
    op.drop_index(op.f('ix_settlement_logs_id'), table_name='settlement_logs')
    op.drop_table('settlement_logs')
    
    # These tables depend on projects (and other tables)
    op.drop_index(op.f('ix_access_grants_id'), table_name='access_grants')
    op.drop_table('access_grants')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_commitments_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    
    # Now we can drop projects table
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    
    # Drop other tables that don't depend on projects
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_legal_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_type'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_state_mstr_id'), table_name='state_mstr')
    op.drop_table('state_mstr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name='users_party_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('documents_project_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('documents_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('settlement_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('commitment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proof_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], name=op.f('settlement_logs_commitment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('settlement_logs_pkey'))
    )
    op.create_index(op.f('ix_settlement_logs_id'), 'settlement_logs', ['id'], unique=False)
    op.create_table('state_mstr',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('state_mstr_pkey')),
    sa.UniqueConstraint('key', name=op.f('state_mstr_key_key'))
    )
    op.create_index(op.f('ix_state_mstr_id'), 'state_mstr', ['id'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('party_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('commitments_party_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('commitments_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('commitments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('commitments_pkey'))
    )
    op.create_index(op.f('ix_commitments_id'), 'commitments', ['id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer_party_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyer_party_id'], ['parties.id'], name=op.f('allocations_buyer_party_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('allocations_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('allocations_pkey'))
    )
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_table('access_grants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('granted_to_party_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('granted_via', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['granted_to_party_id'], ['parties.id'], name=op.f('access_grants_granted_to_party_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('access_grants_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('access_grants_pkey'))
    )
    op.create_index(op.f('ix_access_grants_id'), 'access_grants', ['id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('parties_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('pan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gstn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='parties_pkey'),
    sa.UniqueConstraint('registration_number', name='parties_registration_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_parties_type'), 'parties', ['type'], unique=False)
    op.create_index(op.f('ix_parties_legal_name'), 'parties', ['legal_name'], unique=False)
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('project_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('project_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(length=191), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_project_cost', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('funding_required', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('funds_secured', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('funding_gap', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('media', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disclosures_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_validation_checklist', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('projects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_index(op.f('ix_perdix_mp_projects_project_reference_id'), table_name='perdix_mp_projects')
    op.drop_index(op.f('ix_perdix_mp_projects_id'), table_name='perdix_mp_projects')
    op.drop_table('perdix_mp_projects')
    # ### end Alembic commands ###
